import {
  Activity,
  BarChart2,
  Bot,
  Brain,
  CheckSquare,
  Cpu,
  Database,
  Eye,
  FileCode,
  FileJson,
  FileText,
  FolderTree,
  Gauge,
  Globe,
  Globe2,
  HelpCircle,
  Key,
  LayoutDashboard,
  Link,
  ListTree,
  Lock,
  Map,
  MessageSquare,
  Network,
  Newspaper,
  Radio,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  Terminal,
  TestTube,
  Film,
  Trello,
  TrendingUp,
  Users,
  Zap
} from "lucide-react";

export const NAVIGATION_ITEMS = [
  { name: "Dashboard", path: "/", icon: LayoutDashboard },
  { name: "Publishing", path: "/publishing", icon: Film },
  { name: "Search Intelligence", path: "/search-intelligence", icon: Search },
  { name: "Integrations", path: "/integrations", icon: Network },
  { name: "Registry", path: "/registry", icon: FolderTree },
  { name: "Agents", path: "/agents", icon: Bot },
  { name: "Mission Control", path: "/mission-control", icon: Globe },
  { name: "Automation", path: "/automation", icon: Zap },
  { name: "AI Center", path: "/ai-center", icon: Brain },
  { name: "Analytics", path: "/analytics", icon: BarChart2 },
  { name: "Security", path: "/security", icon: ShieldCheck },
  { name: "Monitoring", path: "/monitoring", icon: Activity },
  { name: "Reports", path: "/reports", icon: FileText },
  { name: "Settings", path: "/settings", icon: Settings },
  { name: "Users", path: "/users", icon: Users },
  { name: "API Keys", path: "/api-keys", icon: Key },
  { name: "Database", path: "/database", icon: Database },
  { name: "Testing", path: "/testing", icon: TestTube },
  { name: "Developer", path: "/developer", icon: Terminal },
  { name: "Help", path: "/help", icon: HelpCircle },
];

